network = "mainnet"
canonical_bn = "http://localhost:5052"

[[post_endpoints]]
name = "blockgauge"
url = "http://localhost:8002/classify"
extra_data = true
compare_rewards = true

[[nodes]]
name = "lighthouse-subscribe-none"
label = "Lighthouse"
url = "http://localhost:5052"
skip_randao_verification = true
