network = "mainnet"
canonical_bn = "http://localhost:5052"

[[post_endpoints]]
name = "blockgauge"
url = "http://localhost:5052/lighthouse/analysis/block_rewards"
extra_data = false
compare_rewards = true

[[nodes]]
name = "lighthouse-subscribe-none"
label = "Lighthouse"
url = "http://localhost:5052"
v3 = true
ssz = false
use_builder = true
skip_randao_verification = true
